{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "[2021-04-22 13:34:33,076] ERROR in app: Exception on /stud [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-b5bb6625172f>\", line 15, in disprec\n",
      "    mycol.insert_one(mydict)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\collection.py\", line 701, in insert_one\n",
      "    session=session),\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\collection.py\", line 615, in _insert\n",
      "    bypass_doc_val, session)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\collection.py\", line 603, in _insert_one\n",
      "    acknowledged, _insert_command, session)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py\", line 1498, in _retryable_write\n",
      "    return self._retry_with_session(retryable, func, s, None)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py\", line 1384, in _retry_with_session\n",
      "    return self._retry_internal(retryable, func, session, bulk)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py\", line 1404, in _retry_internal\n",
      "    server = self._select_server(writable_server_selector, session)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py\", line 1278, in _select_server\n",
      "    server = topology.select_server(server_selector)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\topology.py\", line 243, in select_server\n",
      "    address))\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\topology.py\", line 200, in select_servers\n",
      "    selector, server_timeout, address)\n",
      "  File \"C:\\Users\\Saanya\\Anaconda3\\lib\\site-packages\\pymongo\\topology.py\", line 217, in _select_servers_loop\n",
      "    (self._error_message(selector), timeout, self.description))\n",
      "pymongo.errors.ServerSelectionTimeoutError: No primary available for writes, Timeout: 30s, Topology Description: <TopologyDescription id: 60812df29fad56e3276335bc, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.6c3n1.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed',)>, <ServerDescription ('cluster0-shard-00-01.6c3n1.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed',)>, <ServerDescription ('cluster0-shard-00-02.6c3n1.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.05340000000142027>]>\n",
      "127.0.0.1 - - [22/Apr/2021 13:34:33] \"\u001b[35m\u001b[1mGET /stud?sname=Jas&division=A&elective=Python HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [22/Apr/2021 13:34:33] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask,request\n",
    "import pymongo\n",
    "import dns\n",
    "app = Flask(__name__)\n",
    "\n",
    "@app.route('/stud')\n",
    "def disprec():\n",
    "    myclient=pymongo.MongoClient(\"mongodb+srv://saanya:saanya@cluster0.6c3n1.mongodb.net/myFirstDatabase?retryWrites=true&w=majority\")\n",
    "    mydb=myclient[\"sj\"]\n",
    "    mycol=mydb[\"student\"]\n",
    "    sn=request.args.get('sname')\n",
    "    div1=request.args.get('division')\n",
    "    elective=request.args.get('elective')\n",
    "    mydict={\"studname\":sn,\"div\":div1,\"elective\":elective}\n",
    "    mycol.insert_one(mydict)\n",
    "    return \"Record Inserted...\"\n",
    "                                 \n",
    "if __name__ == '__main__':\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
